import Link from 'next/link';
import Image from 'next/image';
import report from '../../../public/submission/evaluation.json';
import comparison from '../../../public/submission/provider-comparison.json';
import { ProviderComparison } from '@/components/ProviderComparison';
import type { EvalReport } from '@/lib/types';
export default function EvidencePage() {
  return <div className="shell">
    <section className="hero"><div><div className="eyebrow text-series-1">BUILT TO BE INSPECTED</div><h1>Evidence.<br/><span className="text-series-1">Not just a demo.</span></h1><p className="text-sm text-text-secondary leading-6 max-w-2xl">Aegis is a reference trust layer around a fictional banking assistant. The source, evaluation contract, architecture, and measured results are open for review.</p></div><a href="https://github.com/SyedMaaz786/yc-moss-aegis" className="btn" target="_blank" rel="noreferrer">Explore the repository ↗</a></section>
    <div className="grid md:grid-cols-3 gap-4 mb-6">
      <article className="panel p-6"><div className="eyebrow">01 / PRODUCT</div><h2 className="text-xl mt-3 mb-2">The problem & the promise</h2><p className="hint mb-5">Who this protects, what is implemented, acceptance criteria, and explicit limits.</p><a className="text-sm text-series-1" href="/submission/PRD.pdf" target="_blank">Read the PRD ↗</a></article>
      <article className="panel p-6"><div className="eyebrow">02 / DESIGN</div><h2 className="text-xl mt-3 mb-2">Follow the trust boundary</h2><p className="hint mb-5">Every gate from input to release, and the exact role Moss plays in the pipeline.</p><a className="text-sm text-series-1" href="/submission/architecture.svg" target="_blank">Open architecture diagram ↗</a></article>
      <article className="panel p-6"><div className="eyebrow">03 / WALKTHROUGH</div><h2 className="text-xl mt-3 mb-2">Watch the gates in action</h2><p className="hint mb-5">A 3:30 reference walkthrough: live gates, source evidence, evaluation, and provider recovery.</p><Link className="text-sm text-series-1" href="/demo">Watch the walkthrough →</Link></article>
    </div>
    <section className="panel p-6 mb-6"><div className="flex flex-wrap justify-between gap-5 items-start"><div><div className="eyebrow text-series-1">PUBLISHED MEASUREMENT / {report.suiteVersion}</div><h2 className="text-2xl tracking-tight mt-3">{report.passed} of {report.totalCases} regression cases passed</h2><p className="hint mt-2">Recorded {new Date(report.timestamp).toISOString().slice(0,19).replace('T',' ')} UTC. Real Moss retrieval and Groq calls on the development machine.</p></div><Link className="btn" href="/eval">Run it yourself →</Link></div>
      <div className="grid sm:grid-cols-3 gap-5 mt-6"><div><p className="text-2xl text-series-1">{(report.safetyAccuracy*100).toFixed(0)}%</p><p className="hint">Attack blocking · fixed suite</p></div><div><p className="text-2xl text-series-1">{((report.benignSuccessRate??0)*100).toFixed(0)}%</p><p className="hint">Benign answer success</p></div><div><p className="text-2xl">{report.p95LatencyMs.toFixed(0)} ms</p><p className="hint">p95 total turn latency</p></div></div>
      <p className="hint mt-5">This is a public regression suite used during development, not an independent or exhaustive security benchmark. Deployment timing, cold starts, and provider availability vary.</p><a href="/submission/evaluation.json" className="text-xs text-series-1 inline-block mt-3" download>↓ Download the measured report</a>
    </section>
    <ProviderComparison comparison={{ ...comparison, runs: comparison.runs as EvalReport[] }}/>
    <section className="panel p-6 mb-6"><h2 className="text-lg mb-3">Recovery without bypassing the release gate</h2><p className="hint">Groq is the primary generator. If generation fails, the configured HiDevs Gemini backup gets one bounded attempt. Its answer must pass the same privacy, numerical, and grounding checks. A rejected candidate is withheld; it does not trigger another model attempt.</p><p className="hint mt-3">Verified with a local test harness that injected a primary HTTP 503 and received a real, source-checked Gemini answer. This was a controlled fault injection, not an observed production outage.</p><a href="/submission/failover.json" download className="text-xs text-series-1 inline-block mt-4">Download the failover decision receipt ↓</a></section>
    <section className="panel overflow-hidden"><div className="panel-head"><h2 className="text-sm">System architecture</h2><a href="/submission/architecture.svg" download className="text-xs text-series-1">Download SVG ↓</a></div><Image unoptimized src="/submission/architecture.svg" width={1440} height={1050} alt="Aegis architecture: five sequential release gates, backed by Moss local retrieval, evaluations, and isolated private session traces." className="w-full h-auto"/></section>
    <section className="grid md:grid-cols-2 gap-6 mt-6"><div className="panel p-6"><h2 className="text-lg mb-4">Why Moss matters here</h2><p className="hint">Moss retrieves threat patterns, policy context, and supporting sources for the candidate answer. Its native session searches caller-supplied vectors from a bundled MiniLM encoder. Both document and query embeddings use the same model bytes. No vector database or runtime model download is needed.</p><p className="hint mt-3">Moss ranking values are not probabilities. For release thresholds, returned candidates are calibrated against their original normalized vectors. The console distinguishes embedding time from native search time.</p></div><div className="panel p-6"><h2 className="text-lg mb-4">What this does not claim</h2><p className="hint">Semantic overlap cannot prove factual entailment. Numerical checks can catch unsupported amounts but cannot establish every relationship. Pattern guardrails can miss novel attacks. Source integrity assumes the repository’s policy manifest is trusted.</p><p className="hint mt-3">This demo cannot execute banking transactions. Session traces expire and may disappear across serverless restarts. Rate limits are per instance, not a distributed abuse-prevention system.</p></div></section>
  </div>;
}
